bot.token=7361604859:AAGYKiYyFaBVZvY-qJjmfzaEdx240CPm1Qg
bot.username=hockey_match_tracker_bot
monitoring.interval.minutes=1
website.url=https://sportregion2020.ru/
user.agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36